[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy; sys_platform=='darwin'",
    "numpy==1.11.3; python_version=='3.6' and sys_platform=='linux'",
    "numpy==1.14.6; python_version=='3.7' and sys_platform=='linux'",
    "numpy==1.17.5; python_version=='3.8' and sys_platform=='linux'",
    "numpy==1.19.5; python_version=='3.9' and sys_platform=='linux'",
    "numpy==1.21.3; python_version=='3.10' and sys_platform=='linux'",
    "numpy; python_version>='3.11'",
    "Cython>0.28",
]
